In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [12]:

# Load the EMG data from the Excel file
emg_data = pd.read_excel('emg_data.xlsx')

# Drop rows with missing values (NaN)
emg_data = emg_data.dropna()
emg_data

Timestamp  EMG_A0  EMG_A1 Label
0    1.707697e+09      25       0     b
1    1.707697e+09      25      33     b
2    1.707697e+09      23       0     b
3    1.707697e+09      23       0     b
4    1.707697e+09      25       0     b
..            ...     ...     ...   ...
583  1.707697e+09     109       0     d
584  1.707697e+09     109       0     d
585  1.707697e+09     117       0     d
586  1.707697e+09     102       0     d
587  1.707697e+09     107       0     d

[588 rows x 4 columns]

In [15]:
X = emg_data[['EMG_A0', 'EMG_A1']].values
y_str = emg_data['Label'].values


# Use LabelEncoder to convert string labels to numerical values
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y_str)


In [26]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(y_test.shape,y_train.shape)

(118,) (470,)


In [17]:
# Standardize the data using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
# Reshape the data for LSTM input (samples, time steps, features)

X_train_reshaped = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test_reshaped = X_test_scaled.reshape((X_test_scaled.shape[0], 1, X_test_scaled.shape[1]))


In [28]:
# Define the LSTM model
model = Sequential()
model.add(LSTM(50, input_shape=(X_train_reshaped.shape[1], X_train_reshaped.shape[2])))
model.add(Dense(1, activation='sigmoid'))  # Assuming binary classification (adjust for your problem)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [29]:
# Train the model
model.fit(X_train_reshaped, y_train, epochs=10, batch_size=32, validation_data=(X_test_reshaped, y_test))


Epoch 1/10
15/15 [==============================] - 3s 43ms/step - loss: 0.8947 - accuracy: 0.2043 - val_loss: 0.6617 - val_accuracy: 0.3475
Epoch 2/10
15/15 [==============================] - 0s 6ms/step - loss: 0.4760 - accuracy: 0.3319 - val_loss: 0.6272 - val_accuracy: 0.1610
Epoch 3/10
15/15 [==============================] - 0s 5ms/step - loss: 0.0396 - accuracy: 0.3319 - val_loss: 0.5939 - val_accuracy: 0.1017
Epoch 4/10
15/15 [==============================] - 0s 6ms/step - loss: -0.3183 - accuracy: 0.3319 - val_loss: 0.5618 - val_accuracy: 0.0932
Epoch 5/10
15/15 [==============================] - 0s 6ms/step - loss: -0.7068 - accuracy: 0.3319 - val_loss: 0.5305 - val_accuracy: 0.0847
Epoch 6/10
15/15 [==============================] - 0s 6ms/step - loss: -1.1694 - accuracy: 0.3319 - val_loss: 0.5026 - val_accuracy: 0.0847
Epoch 7/10
15/15 [==============================] - 0s 6ms/step - loss: -1.7160 - accuracy: 0.3319 - val_loss: 0.4761 - val_accuracy: 0.0847
Epoch 8/10
15/1

In [30]:
# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')


4/4 [==============================] - 0s 4ms/step - loss: 0.4125 - accuracy: 0.0847
Test Loss: 0.4124651551246643, Test Accuracy: 0.08474576473236084


In [31]:
# Save the trained model
model.save('emg_label_prediction_model.h5')
print('Model saved as emg_label_prediction_model.h5')

# Save label encoder for future use
import joblib
joblib.dump(label_encoder, 'label_encoder.joblib')

Model saved as emg_label_prediction_model.h5


['label_encoder.joblib']

In [32]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split

# Generate sample data
np.random.seed(42)
X = np.random.random((100, 10, 1))  # Sample input data with shape (samples, timesteps, features)
y = np.random.randint(0, 2, size=(100,))  # Binary labels (0 or 1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the LSTM model
model = Sequential()
model.add(LSTM(50, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dense(1, activation='sigmoid'))  # Output layer for binary classification

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}, Test Accuracy: {accuracy}')

# Make predictions on a new test case (adjust as per your actual data)
new_test_case = np.random.random((1, 10, 1
                                 
prediction = model.predict(new_test_case)

print(f'Predicted Probability: {prediction[0][0]}')
predicted_label = 1 if prediction[0][0] > 0.5 else 0
print(f'Predicted Label: {predicted_label}')


Epoch 1/10
2/2 [==============================] - 3s 682ms/step - loss: 0.7023 - accuracy: 0.4688 - val_loss: 0.7044 - val_accuracy: 0.4375
Epoch 2/10
2/2 [==============================] - 0s 47ms/step - loss: 0.7000 - accuracy: 0.4688 - val_loss: 0.6999 - val_accuracy: 0.4375
Epoch 3/10
2/2 [==============================] - 0s 46ms/step - loss: 0.6962 - accuracy: 0.4688 - val_loss: 0.6963 - val_accuracy: 0.4375
Epoch 4/10
2/2 [==============================] - 0s 46ms/step - loss: 0.6936 - accuracy: 0.5000 - val_loss: 0.6933 - val_accuracy: 0.5625
Epoch 5/10
2/2 [==============================] - 0s 48ms/step - loss: 0.6919 - accuracy: 0.5156 - val_loss: 0.6910 - val_accuracy: 0.5625
Epoch 6/10
2/2 [==============================] - 0s 48ms/step - loss: 0.6908 - accuracy: 0.5312 - val_loss: 0.6895 - val_accuracy: 0.5625
Epoch 7/10
2/2 [==============================] - 0s 47ms/step - loss: 0.6911 - accuracy: 0.5312 - val_loss: 0.6882 - val_accuracy: 0.5625
Epoch 8/10
2/2 [==========

In [34]:
new_test_case
X


array([[[0.37454012],
        [0.95071431],
        [0.73199394],
        [0.59865848],
        [0.15601864],
        [0.15599452],
        [0.05808361],
        [0.86617615],
        [0.60111501],
        [0.70807258]],

       [[0.02058449],
        [0.96990985],
        [0.83244264],
        [0.21233911],
        [0.18182497],
        [0.18340451],
        [0.30424224],
        [0.52475643],
        [0.43194502],
        [0.29122914]],

       [[0.61185289],
        [0.13949386],
        [0.29214465],
        [0.36636184],
        [0.45606998],
        [0.78517596],
        [0.19967378],
        [0.51423444],
        [0.59241457],
        [0.04645041]],

       [[0.60754485],
        [0.17052412],
        [0.06505159],
        [0.94888554],
        [0.96563203],
        [0.80839735],
        [0.30461377],
        [0.09767211],
        [0.68423303],
        [0.44015249]],

       [[0.12203823],
        [0.49517691],
        [0.03438852],
        [0.9093204 ],
        [0.25877998],
  

In [50]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical

# Load your labeled dataset from the Excel file
# Replace 'new_data.xlsx' with the path to your new data file
data = pd.read_excel('emg_data.xlsx')

# Extract features (EMG_A0, EMG_A1) and labels
X = data[['EMG_A0', 'EMG_A1']].values
y = data['Label'].values

# Encode categorical labels into numerical values
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Normalize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Create sequences for the LSTM model
sequence_length = 10  # Adjust this based on the length of sequences you want
X_sequence = []
y_sequence = []

for i in range(len(X_scaled) - sequence_length + 1):
    X_sequence.append(X_scaled[i:i+sequence_length, :])
    y_sequence.append(y_encoded[i+sequence_length-1])

X_sequence = np.array(X_sequence)
y_sequence = np.array(y_sequence)

# Convert labels to one-hot encoding for multi-class classification
y_sequence_onehot = to_categorical(y_sequence, num_classes=len(label_encoder.classes_))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_sequence, y_sequence_onehot, test_size=0.2, random_state=42)

# Define the LSTM model
model = Sequential()
model.add(LSTM(units=50, input_shape=(sequence_length, X_scaled.shape[1]), return_sequences=True))
model.add(LSTM(units=50))
model.add(Dense(units=len(label_encoder.classes_), activation='softmax'))  # Multi-class classification

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}')

# Save the trained model for later use
model.save('trained_model_multiclass.h5')


Epoch 1/10
12/12 [==============================] - 3s 60ms/step - loss: 1.2713 - accuracy: 0.6162 - val_loss: 1.1193 - val_accuracy: 0.7097
Epoch 2/10
12/12 [==============================] - 0s 9ms/step - loss: 0.9461 - accuracy: 0.7054 - val_loss: 0.8097 - val_accuracy: 0.6882
Epoch 3/10
12/12 [==============================] - 0s 9ms/step - loss: 0.6744 - accuracy: 0.7135 - val_loss: 0.6870 - val_accuracy: 0.7742
Epoch 4/10
12/12 [==============================] - 0s 9ms/step - loss: 0.5377 - accuracy: 0.8081 - val_loss: 0.6419 - val_accuracy: 0.7849
Epoch 5/10
12/12 [==============================] - 0s 10ms/step - loss: 0.4592 - accuracy: 0.8405 - val_loss: 0.5789 - val_accuracy: 0.7957
Epoch 6/10
12/12 [==============================] - 0s 9ms/step - loss: 0.4192 - accuracy: 0.8486 - val_loss: 0.5749 - val_accuracy: 0.8172
Epoch 7/10
12/12 [==============================] - 0s 9ms/step - loss: 0.3726 - accuracy: 0.8865 - val_loss: 0.4974 - val_accuracy: 0.8495
Epoch 8/10
12/12 [

C:\Users\anshi\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [51]:
# Assuming you already have a trained model named 'model'

# Load new data for testing
# Replace 'new_data.xlsx' with the path to your new data file
new_data = pd.read_excel('new_data.xlsx')

# Extract features (EMG_A0, EMG_A1) from the new data
X_new = new_data[['EMG_A0', 'EMG_A1']].values

# Normalize the features using the same scaler used during training
X_new_scaled = scaler.transform(X_new)

# Create sequences for the LSTM model
X_new_sequence = []

for i in range(len(X_new_scaled) - sequence_length + 1):
    X_new_sequence.append(X_new_scaled[i:i+sequence_length, :])

X_new_sequence = np.array(X_new_sequence)

# Make predictions using the trained model
predictions = model.predict(X_new_sequence)
print(predictions)
# Convert predictions to binary classes (0 or 1) based on a threshold
threshold = 0.5  # Adjust as needed
binary_predictions = (predictions > threshold).astype(int)

# Display the predictions
print("Predictions:")
print(binary_predictions)


18/18 [==============================] - 1s 3ms/step
[[0.52633995 0.06748138 0.40191683 0.00426186]
 [0.31311753 0.07013524 0.6127049  0.00404233]
 [0.19167757 0.06251336 0.741874   0.00393511]
 ...
 [0.01352136 0.01929396 0.0094422  0.9577424 ]
 [0.01070263 0.0143078  0.00731391 0.9676756 ]
 [0.00864981 0.0109062  0.00587644 0.9745676 ]]
Predictions:
[[1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [53]:
print(binary_predictions)

[[1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 ...
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]]


In [49]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.utils import to_categorical

# Load your labeled dataset from the Excel file
# Replace 'emg_data.xlsx' with the path to your data file
data = pd.read_excel('emg_data.xlsx')

# Check if the dataset has at least one sample
if data.shape[0] == 0:
    print("Error: The dataset does not contain any samples.")
else:
    # Extract features (EMG_A0, EMG_A1) and labels
    X = data[['EMG_A0', 'EMG_A1']].values
    y = data['Label'].values

    # Check if there are samples to fit the StandardScaler
    if X.shape[0] > 0:
        # Encode categorical labels into numerical values
        label_encoder = LabelEncoder()
        y_encoded = label_encoder.fit_transform(y)

        # Save label encoder classes for later use
        np.save('label_encoder_classes.npy', label_encoder.classes_)

        # Normalize the features
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        # Create sequences for the LSTM model
        sequence_length = 10  # Adjust this based on the length of sequences you want
        X_sequence = []
        y_sequence = []

        for i in range(len(X_scaled) - sequence_length + 1):
            X_sequence.append(X_scaled[i:i + sequence_length, :])
            y_sequence.append(y_encoded[i + sequence_length - 1])

        X_sequence = np.array(X_sequence)
        y_sequence = np.array(y_sequence)

        # Convert labels to one-hot encoding for multi-class classification
        num_classes = len(np.unique(y_encoded))  # Number of unique classes
        y_sequence_onehot = to_categorical(y_sequence, num_classes=num_classes)

        # Split the data into training and testing sets
        X_train, X_test, y_train, y_test = train_test_split(X_sequence, y_sequence_onehot, test_size=0.2, random_state=42)

        # Define the LSTM model
        model = Sequential()
        model.add(LSTM(units=50, input_shape=(sequence_length, X_scaled.shape[1]), return_sequences=True))
        model.add(LSTM(units=50))
        model.add(Dense(units=num_classes, activation='softmax'))  # Adjusted to use num_classes

        # Compile the model
        model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

        # Train the model
        model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

        # Save the trained model for later use
        model.save('trained_model_multiclass.h5')
    else:
        print("Error: No samples to fit the StandardScaler.")


Epoch 1/10
12/12 [==============================] - 6s 90ms/step - loss: 1.2706 - accuracy: 0.6784 - val_loss: 1.1257 - val_accuracy: 0.7742
Epoch 2/10
12/12 [==============================] - 0s 10ms/step - loss: 0.9686 - accuracy: 0.7676 - val_loss: 0.8509 - val_accuracy: 0.7634
Epoch 3/10
12/12 [==============================] - 0s 10ms/step - loss: 0.6840 - accuracy: 0.7676 - val_loss: 0.7158 - val_accuracy: 0.7527
Epoch 4/10
12/12 [==============================] - 0s 10ms/step - loss: 0.5458 - accuracy: 0.7946 - val_loss: 0.6559 - val_accuracy: 0.7849
Epoch 5/10
12/12 [==============================] - 0s 10ms/step - loss: 0.4742 - accuracy: 0.8243 - val_loss: 0.6195 - val_accuracy: 0.8065
Epoch 6/10
12/12 [==============================] - 0s 10ms/step - loss: 0.4189 - accuracy: 0.8486 - val_loss: 0.5579 - val_accuracy: 0.8172
Epoch 7/10
12/12 [==============================] - 0s 10ms/step - loss: 0.3955 - accuracy: 0.8486 - val_loss: 0.5232 - val_accuracy: 0.8280
Epoch 8/10
12

C:\Users\anshi\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Load your sample data from Excel
data = pd.read_excel("emg_data.xlsx")

# Separate features (EMG_A0 and EMG_A1) and labels (Label)
X = data[['EMG_A0', 'EMG_A1']]
y = data['Label']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Save the model to a file
joblib.dump(rf_model, "random_forest_model.joblib")

# Make predictions on the test set
y_pred = rf_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print classification report
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.82
Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.93      0.95        41
           1       0.64      0.67      0.65        27
           2       0.88      0.84      0.86        25
           3       0.74      0.80      0.77        25

    accuracy                           0.82       118
   macro avg       0.81      0.81      0.81       118
weighted avg       0.83      0.82      0.82       118



In [59]:
import pandas as pd
import joblib

# Load the saved model
loaded_model = joblib.load("random_forest_model.joblib")
data = pd.read_excel("new_data.xlsx")

# Assuming 'new_data' is your new dataset with columns 'EMG_A0' and 'EMG_A1'
new_predictions = loaded_model.predict(data[['EMG_A0', 'EMG_A1']])

# Display the predicted labels
print("Predicted Labels for new data:")
print(new_predictions)


Predicted Labels for new data:
[0 2 2 2 0 3 2 1 3 0 1 0 0 0 2 3 2 0 2 2 1 1 2 2 2 3 2 2 0 0 3 1 1 0 3 2 0
 0 1 0 2 1 0 0 1 2 2 3 1 2 1 1 0 0 3 3 2 0 1 0 3 1 0 2 2 0 0 2 3 0 1 3 2 1
 0 0 3 0 0 3 0 1 0 0 0 3 0 2 0 2 0 2 1 3 1 2 1 2 2 1 0 0 1 2 3 3 1 1 0 3 3
 2 0 0 1 3 1 1 1 3 1 3 3 0 0 0 0 2 0 0 1 1 2 0 1 1 2 3 3 2 3 3 2 2 3 2 0 3
 1 1 3 0 1 0 2 2 2 3 0 2 0 0 3 3 3 0 1 1 0 2 3 3 3 3 0 3 0 1 2 2 0 0 2 1 3
 1 0 3 1 0 0 1 2 3 0 2 2 0 3 3 0 3 0 0 1 0 0 1 2 3 3 2 3 2 3 1 0 0 1 3 1 0
 0 2 0 2 0 2 0 3 0 1 0 0 1 2 2 2 1 1 0 2 0 2 3 0 1 1 2 2 3 1 2 0 1 1 0 0 0
 3 2 2 1 0 0 2 0 3 0 2 3 1 0 1 0 1 0 3 2 2 2 3 1 2 1 2 0 0 1 0 1 1 3 0 0 1
 1 2 1 2 2 2 1 0 0 1 2 3 3 2 2 0 2 0 2 0 0 1 3 3 3 1 1 0 3 3 0 0 1 0 2 3 2
 1 0 2 1 3 1 2 1 1 2 1 2 1 0 0 2 0 0 3 3 1 2 2 2 1 0 1 0 3 2 0 2 0 3 0 1 2
 0 2 1 0 2 2 0 0 1 1 3 3 0 3 1 0 3 0 0 0 0 0 1 0 3 2 2 0 1 3 2 1 3 2 0 3 2
 3 3 1 3 0 2 2 1 0 2 0 0 2 1 2 0 2 2 3 3 0 2 0 0 0 2 0 0 0 3 0 1 3 1 1 1 2
 1 3 1 2 0 2 0 3 2 2 2 0 0 3 1 2 1 1 0 3 2 0 0 2 1 0 3 0 2 0 1 0 2 2 